# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "referral_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("patient_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("approximate_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("F", "Female"),
                            ("M", "Male"),
                            ("O", "Other"),
                            ("U", "Unknown"),
                        ],
                        default="F",
                        max_length=2,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("alternative_phone", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("county", models.CharField(default="Nairobi", max_length=100)),
                ("sub_county", models.CharField(blank=True, max_length=100)),
                ("landmark", models.CharField(blank=True, max_length=255)),
                (
                    "referral_source",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Public / Private Hospital"),
                            ("HEALTH_CENTRE", "Health Centre / Clinic"),
                            ("COMMUNITY_WORKER", "Community Health Promoter"),
                            ("SELF_FAMILY", "Self / Family Referral"),
                            ("OTHER_HOSPICE", "Other Hospice / Palliative Unit"),
                            ("RELIGIOUS_GROUP", "Faith-Based / Community Group"),
                            ("OTHER", "Other Source"),
                        ],
                        default="HOSPITAL",
                        max_length=30,
                    ),
                ),
                (
                    "referring_facility",
                    models.CharField(
                        help_text="e.g. Kenyatta National Hospital, Texas Cancer Centre",
                        max_length=200,
                    ),
                ),
                (
                    "referring_clinician_name",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "referring_clinician_phone",
                    models.CharField(blank=True, max_length=30),
                ),
                (
                    "referring_clinician_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("referral_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine (Review within 5 days)"),
                            ("URGENT", "Urgent (Review within 48 hours)"),
                            (
                                "EMERGENCY",
                                "Emergency / Severe Distress (Review within 24 hours)",
                            ),
                        ],
                        db_index=True,
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("CONVERTED", "Converted to Patient"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "primary_diagnosis",
                    models.CharField(
                        help_text="e.g. Ca Breast Stage IV with bone metastases",
                        max_length=255,
                    ),
                ),
                (
                    "reason_for_referral",
                    models.TextField(
                        help_text="Pain management, severe dyspnea, family counseling, end-of-life care"
                    ),
                ),
                (
                    "clinical_summary",
                    models.TextField(
                        blank=True,
                        help_text="History of current illness, treatments received, ECOG performance",
                    ),
                ),
                ("current_medications", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "converted_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originating_referrals",
                        to="patients.patient",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
                "ordering": ["-referral_date", "-created_at"],
            },
        ),
    ]
