# Generated by Django 5.1.15 on 2026-08-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Staff profile photograph",
                null=True,
                upload_to="staff_avatars/",
            ),
        ),
    ]
