# Generated by Django 5.2.17 on 2026-08-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_mfa_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mfa_secret",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
