# Generated by Django 5.2.17 on 2026-08-26 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_mfa_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mfa_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, staff accounts require TOTP authenticator code verification at login.",
                        verbose_name="Multi-Factor Authentication (Google Authenticator) Enabled",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Configuration",
                "verbose_name_plural": "Security Configurations",
            },
        ),
    ]
