# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("PHONE_CALL", "Telephone Call"),
                            ("SMS", "SMS Message"),
                            ("EMAIL", "Email Communication"),
                            ("FAMILY_MEETING", "Family Conference / Meeting"),
                            ("MDT_COMMUNICATION", "Internal Multidisciplinary Note"),
                            (
                                "EXTERNAL_LIAISON",
                                "External Hospital / Clinician Liaison",
                            ),
                        ],
                        default="PHONE_CALL",
                        max_length=30,
                    ),
                ),
                (
                    "communication_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Patient, Primary Caregiver, Referring Doctor, etc.",
                        max_length=150,
                    ),
                ),
                ("phone_or_email", models.CharField(blank=True, max_length=100)),
                (
                    "summary",
                    models.TextField(help_text="Summary of conversation / discussion"),
                ),
                ("followup_required", models.BooleanField(default=False)),
                ("followup_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication Record",
                "verbose_name_plural": "Communication Records",
                "ordering": ["-communication_date"],
            },
        ),
    ]
