# Generated by Django 5.2.17 on 2026-08-22 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
        ("patients", "0004_alter_patient_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="communicationrecord",
            index=models.Index(
                fields=["patient", "communication_date"], name="comm_patient_date_idx"
            ),
        ),
    ]
