"""
Standard Nairobi Hospice Palliative Diagnoses and Disease Classifications
Extracted from Hospice Access Database (107 Standard Classifications).
"""

HOSPICE_DIAGNOSES = [
    "Acute lymphoblastic leukemia",
    "Acute myeloid leukemia",
    "Adrenocortical carcinoma",
    "AFP - Acute Flaccid Paralysis",
    "Anal cancer",
    "Angiosarcoma",
    "Astrocytoma",
    "Basal cell carcinoma",
    "Bladder cancer",
    "BM - Bacterial Meningitis",
    "Breast cancer",
    "Burkitt lymphoma",
    "CALV - Liver Cancer",
    "CAOE - Oesophageal Cancer",
    "CAOT - Cancer (Other)",
    "CAOV - Ovarian Cancer",
    "CAPN - Pancreatic Cancer",
    "CAPR - Prostate Cancer",
    "Carcinoid tumor",
    "CAST - Stomach Cancer",
    "CCF - Congestive Cardiac Failure",
    "Cervical cancer",
    "Chondrosarcoma",
    "Chordoma",
    "Chronic lymphocytic leukemia",
    "Chronic myeloid leukemia",
    "Classical Hodgkin lymphoma",
    "CM - Cryptococcal Meningitis",
    "Colorectal cancer",
    "Craniopharyngioma",
    "Cutaneous lymphoma",
    "Cutaneous melanoma",
    "CVA - Cerebrovascular Accident",
    "Diffuse large B-cell lymphoma",
    "Endometrial cancer",
    "Ependymoma",
    "Esophageal cancer",
    "Ewing sarcoma",
    "Fibrosarcoma",
    "Follicular lymphoma",
    "Gallbladder cancer",
    "Glioblastoma",
    "Hairy cell leukemia",
    "HIV - HIV/AIDS",
    "HPL - Hemiplegia (left side)",
    "HPR - Hemiplegia (right side)",
    "HPT - Hepatoma",
    "HTN - Hypertension",
    "Kaposi sarcoma",
    "Kidney cancer",
    "KS - Kaposi's Sarcoma",
    "Laryngeal cancer",
    "LC - Liver Cirrhosis",
    "Leiomyosarcoma",
    "Liposarcoma",
    "Liver cancer",
    "Lung cancer",
    "Mantle cell lymphoma",
    "Medulloblastoma",
    "Meningioma",
    "Merkel cell carcinoma",
    "Mesothelioma",
    "Mucosal melanoma",
    "Multiple myeloma",
    "Nasopharyngeal cancer",
    "NEUR - Neurological",
    "Neuroblastoma",
    "Nodular lymphocyte-predominant Hodgkin lymphoma",
    "Non-seminomatous germ cell tumor",
    "Ocular melanoma",
    "Oligodendroglioma",
    "Oral cancer",
    "Osteosarcoma",
    "Ovarian cancer",
    "Ovarian germ cell tumor",
    "Pancreatic cancer",
    "Pancreatic neuroendocrine tumor",
    "Paraganglioma",
    "Penile cancer",
    "Peripheral T-cell lymphoma",
    "Pheochromocytoma",
    "Plasmacytoma",
    "PP - Paraplegia",
    "Prostate cancer",
    "QP - Quadriplegia",
    "Retinoblastoma",
    "Rhabdomyosarcoma",
    "RHD - Rheumatic Heart Disease",
    "SCD - Sickle Cell Disease",
    "Seminoma",
    "Smoldering multiple myeloma",
    "Spinal astrocytoma",
    "Spinal ependymoma",
    "Squamous cell carcinoma",
    "Stomach Cancer",
    "Synovial sarcoma",
    "TB - (Pulmonary) Tuberculosis",
    "T-cell leukemia",
    "Testicular cancer",
    "Thymoma",
    "Thyroid cancer",
    "TSS - Tropical Splenomegaly Syndrome",
    "URTI - Upper Respiratory Tract Infection",
    "Vaginal cancer",
    "Vulvar cancer",
    "Wilms tumor",
]
