"""
Official Kenya Administrative Geographies (Counties, Sub-Counties/Constituencies, Wards).
"""

KENYA_LOCATIONS = {
    "Nairobi": {
        "Kibra": ["Makina", "Laini Saba", "Lindi", "Sarang'ombe", "Woodley/Kenyatta Golf Course"],
        "Dagoretti North": ["Kilimani", "Kawangware", "Gatina", "Kileleshwa", "Kabiro"],
        "Dagoretti South": ["Mutu-ini", "Ng'ando", "Riruta", "Uthiru/Ruthimitu", "Waithaka"],
        "Lang'ata": ["Karen", "Nairobi West", "Mugumo-ini", "South C", "Nyayo Highrise"],
        "Westlands": ["Kitisuru", "Parklands/Highridge", "Karura", "Kangemi", "Mountain View"],
        "Starehe": ["Nairobi Central", "Ngara", "Pangani", "Ziwani/Kariokor", "Landi Mawe", "Nairobi South"],
        "Kamukunji": ["Pumwani", "Eastleigh North", "Eastleigh South", "Airbase", "California"],
        "Makadara": ["Maringo/Hamza", "Viwandani", "Harambee", "Makongeni"],
        "Embakasi East": ["Upper Savanna", "Lower Savanna", "Embakasi", "Utawala", "Mihang'o"],
        "Embakasi West": ["Umoja I", "Umoja II", "Mowlem", "Kariobangi South"],
        "Embakasi South": ["Imara Daima", "Kwa Njenga", "Kwa Reuben", "Pipeline", "Kware"],
        "Embakasi North": ["Kariobangi North", "Dandora Area I", "Dandora Area II", "Dandora Area III", "Dandora Area IV"],
        "Embakasi Central": ["Kayole North", "Kayole Central", "Kayole South", "Komarock", "Matopeni/Spring Valley"],
        "Kasarani": ["Clay City", "Mwiki", "Kasarani", "Njiru", "Ruai"],
        "Roysambu": ["Roysambu", "Garden Estate", "Ridgeways", "Githurai", "Kahawa West", "Zimmerman", "Kahawa"],
        "Ruaraka": ["Babadogo", "Utalii", "Mathare North", "Lucky Summer", "Korogocho"],
        "Mathare": ["Hospital", "Mabatini", "Huruma", "Ngei", "Mlango Kubwa", "Kiamaiko"]
    },
    "Kiambu": {
        "Thika Town": ["Township", "Kamenu", "Hospital", "Gatuanyaga", "Ngoliba"],
        "Ruiru": ["Gitothua", "Biashara", "Gatongora", "Kahawa/Sukari", "Kahawa Wendani", "Kiuu", "Mwiki", "Mwihoko"],
        "Juja": ["Murera", "Theta", "Juja", "Witeithie", "Kalimoni"],
        "Kiambu": ["Ting'ang'a", "Ndumberi", "Riabai", "Township"],
        "Kikuyu": ["Karai", "Nachu", "Sigona", "Kikuyu", "Kinoo"],
        "Kabete": ["Gitaru", "Muguga", "Nyadhuna", "Kabete", "Uthiru"],
        "Limuru": ["Bibirioni", "Limuru Central", "Ndeiya", "Limuru East", "Ngecha Tigoni"],
        "Githunguri": ["Githunguri", "Githiga", "Ikinu", "Ngewa", "Komothai"],
        "Kiambaa": ["Cianda", "Karuri", "Ndenderu", "Muchatha", "Kihara"],
        "Gatundu South": ["Kiamwangi", "Kiganjo", "Ndodarugu", "Ngenda"],
        "Gatundu North": ["Gituamba", "Githobokoni", "Chania", "Mang'u"],
        "Lari": ["Kinale", "Kijabe", "Nyanduma", "Kamburu", "Lari/Kirenga"]
    },
    "Machakos": {
        "Machakos Town": ["Kalama", "Mua", "Mutituni", "Machakos Central", "Mumbuni North", "Muvuti/Kiima-Kimwe", "Kola"],
        "Mavoko": ["Athi River", "Kinanie", "Muthwani", "Syokimau/Mulolongo"],
        "Mwala": ["Mbiuni", "Makutano/Mwala", "Masii", "Muthetheni", "Wamunyu", "Kibauni"],
        "Kangundo": ["Kangundo Central", "Kangundo East", "Kangundo North", "Kangundo West"],
        "Matungulu": ["Tala", "Matungulu North", "Matungulu East", "Matungulu West", "Kyeleni"],
        "Yatta": ["Ndalani", "Matuu", "Kithimani", "Ikombe", "Katangi"],
        "Kathiani": ["Mitaboni", "Kathiani Central", "Upper Kaewa/Kaani", "Lower Kaewa/Kaani"],
        "Masinga": ["Kivaa", "Masinga Central", "Ekalakala", "Muthesya", "Ndithini"]
    },
    "Kajiado": {
        "Kajiado North": ["Olkeri", "Ongata Rongai", "Nkaimurunya", "Oloolua", "Ngong"],
        "Kajiado East": ["Kitengela", "Oloosirkon/Sholinke", "Kenyawa-Poka", "Imaroro", "Kaputiei North"],
        "Kajiado Central": ["Purko", "Ildamat", "Dalalekutuk", "Matapato North", "Matapato South"],
        "Kajiado West": ["Keekonyokie", "Iloodokilani", "Magadi", "Ewuaso Oonkidong'i", "Mosiro"],
        "Kajiado South": ["Entonet/Lenkisim", "Mbirikani/Eselenkei", "Kuku", "Rombo", "Kimana"]
    },
    "Nakuru": {
        "Nakuru Town East": ["Biashara", "Kivumbini", "Flamingo", "Menengai", "Nakuru East"],
        "Nakuru Town West": ["Barut", "London", "Kaptembwo", "Kapkures", "Rhoda", "Shaabab"],
        "Naivasha": ["Biashara", "Hells Gate", "Lake View", "Maiella", "Olkaria", "Naivasha East", "Viwandani"],
        "Gilgil": ["Gilgil", "Elementaita", "Mbaruk/Eburu", "Malewa West", "Murindat"],
        "Molo": ["Mariashoni", "Elburgon", "Turi", "Molo"],
        "Njoro": ["Mau Narok", "Mauche", "Kihingo", "Nessuit", "Lare", "Njoro"],
        "Rongai": ["Menengai West", "Soin", "Visoi", "Mosop", "Solai"],
        "Subukia": ["Subukia", "Waseges", "Kabazi"],
        "Bahati": ["Dundori", "Kabatini", "Kiamaina", "Bahati", "Lanet/Umoja"],
        "Kuresoi South": ["Amalo", "Keringet", "Kiptagich", "Tinet"],
        "Kuresoi North": ["Kiptororo", "Nyota", "Sirikwa", "Kamara"]
    },
    "Mombasa": {
        "Mvita": ["Mji wa Kale/Makadara", "Tudor", "Tononoka", "Shimanzi/Ganjoni", "Majengo"],
        "Nyali": ["Frere Town", "Ziwa la Ng'ombe", "Mkomani", "Kongowea", "Kadzandani"],
        "Kisauni": ["Mjambere", "Junda", "Bamburi", "Mwakirunge", "Mtopanga", "Magogoni", "Shanzu"],
        "Likoni": ["Mtongwe", "Shika Adabu", "Bofu", "Likoni", "Timbwani"],
        "Changamwe": ["Port Reitz", "Kipevu", "Airport", "Changamwe", "Chaani"],
        "Jomvu": ["Jomvu Kuu", "Miritini", "Mikindani"]
    },
    "Kisumu": {
        "Kisumu Central": ["Railways", "Migosi", "Shaurimoyo Kaloleni", "Market Milimani", "Kondele", "Nyalenda A"],
        "Kisumu East": ["Kajulu", "Kolwa East", "Manyatta B", "Nyalenda B", "Kolwa Central"],
        "Kisumu West": ["South West Kisumu", "Central Kisumu", "Kisumu North", "West Kisumu", "North West Kisumu"],
        "Nyando": ["East Kano/Wawidhi", "Awasi/Onjiko", "Ahero", "Kabonyo/Kanyagwal", "Kobura"],
        "Muhoroni": ["Miwani", "Ombeyi", "Masogo/Nyang'oma", "Chemelil", "Muhoroni/Koru"],
        "Nyakach": ["South West Nyakach", "North Nyakach", "Central Nyakach", "West Nyakach", "South East Nyakach"],
        "Seme": ["West Seme", "Central Seme", "East Seme", "North Seme"]
    },
    "Uasin Gishu": {
        "Ainabkoi": ["Kapsoya", "Kaptagat", "Ainabkoi/Olare"],
        "Kapseret": ["Simat/Kapseret", "Kipkenyo", "Ngeria", "Megun", "Langas"],
        "Kesses": ["Racecourse", "Cheptiret/Kipchamo", "Tulwet/Chuiyat", "Tarakwa"],
        "Moiben": ["Tembelio", "Sergoit", "Karuna/Meibeki", "Moiben", "Kimumu"],
        "Soy": ["Moi's Bridge", "Kapkures", "Ziwa", "Segero/Barsombe", "Kipsomba", "Soy", "Kuinet/Kapsuswa"],
        "Turbo": ["Ngenyilel", "Tapsagoi", "Kamagut", "Kiplombe", "Kapsaos", "Huruma"]
    },
    "Murang'a": {
        "Kiharu": ["Wangu", "Mugoiri", "Mbiri", "Township", "Murarandia", "Gaturi"],
        "Kandara": ["Ng'araria", "Muruka", "Kagundu-ini", "Gaichanjiru", "Ithiru", "Ruchu"],
        "Maragua": ["Kimorori/Wempa", "Makuyu", "Kambiti", "Kamahuha", "Ichagaki", "Nginda"],
        "Gatanga": ["Kariara", "Gatanga", "Kakuzi/Mitubiri", "Mugumo-ini", "Kihumbu-ini"],
        "Mathioya": ["Gitugi", "Kiru", "Kamachamu"],
        "Kangema": ["Kanyenya-ini", "Muguru", "Rwathia"],
        "Kigumo": ["Kahumbu", "Kigumo", "Kangari", "Kinyona", "Muthithi"]
    },
    "Nyeri": {
        "Nyeri Town": ["Kiganjo/Mathari", "Rware", "Gatitu/Muruguru", "Ruring'u", "Kamakwa/Mukaro"],
        "Mathira": ["Ruguru", "Magutu", "Iria-ini", "Konyu", "Kirimukuyu", "Karatina Town"],
        "Othaya": ["Mahiga", "Iria-ini", "Chinga", "Karima"],
        "Tetu": ["Dedan Kimathi", "Wamagana", "Aguthi-Gaaki"],
        "Mukurweini": ["Gikondi", "Rugi", "Mukurwe-ini West", "Mukurwe-ini Central"],
        "Kieni": ["Mweiga", "Naromoru Kiamathaga", "Mwiyogo/Endarasha", "Mugunda", "Gatarakwa", "Thegu River", "Kabaru", "Gakawa"]
    },
    "Baringo": {"Baringo Central": ["Kabarnet", "Sacho", "Tenges", "Ewalel Chapchap", "Kapropita"], "Baringo North": ["Barwessa", "Saimo Kipsaraman", "Kabartonjo", "Bartabwa"], "Baringo South": ["Marigat", "Ilchamus", "Mochongoi", "Mukutani"], "Eldama Ravine": ["Lembus", "Ravine", "Mumberes/Maji Mazuri"], "Mogotio": ["Mogotio", "Emining", "Kisanana"], "Tiaty": ["Tirioko", "Kolowa", "Ribkwo", "Silale", "Tangulbei/Korossi", "Churo/Amaya"]},
    "Bomet": {"Bomet Central": ["Silibwet Township", "Ndaraweta", "Singorwet", "Chesoen", "Mutarakwa"], "Bomet East": ["Longisa", "Kembu", "Chemaner", "Merigi", "Kipreres"], "Chepalungu": ["Sigor", "Kong'asis", "Chebunyo", "Nyangores", "Siongiroi"], "Konoin": ["Kimulot", "Mogogosiek", "Boito", "Embomos", "Chepchabas"], "Sotik": ["Ndanai/Abosi", "Chemagel", "Kipsonoi", "Kapletundo", "Rongena/Manaret"]},
    "Bungoma": {"Bumula": ["Bumula", "Khasoko", "Kabula", "Kimaeti", "South Bukusu", "Siboti"], "Kabuchai": ["Luhya/Bwake", "Mukuyuni", "Chwele/Kabuchai", "West Nalondo"], "Kanduyi": ["Bukembe West", "Bukembe East", "Township", "Khalaba", "Musikoma", "East Sang'alo", "Marakaru/Tuuti", "Sang'alo West"], "Kimilili": ["Kibingei", "Kimilili", "Maeni", "Kamukuywa"], "Mt Elgon": ["Cheptais", "Chesikaki", "Chepyuk", "Kapkateny", "Kaptama", "Elgon"], "Sirisia": ["Namwwamba", "Malakisi/South Kulisiru", "Lwandanyi"], "Tongaren": ["Mbakalo", "Naitiri/Kabuyefwe", "Milima", "Ndalu/Tabani", "Tongaren", "Soysambu/Mitua"], "Webuye East": ["Mihuu", "Ndivisi", "Maraka"], "Webuye West": ["Sitikho", "Matulo", "Bokoli"]},
    "Busia": {"Budalangi": ["Port Victoria", "Namboboto Nambuku", "Bwiri"], "Funyula": ["Nambale", "Ageng'a Nanguba", "Bwire"], "Matayos": ["Bukhayo West", "Mayenje", "Matayos South", "Busia Township", "Burumba"], "Nambale": ["Nambale Township", "Bukhayo North/Waltsi", "Bukhayo East", "Bukhayo Central"], "Teso North": ["Malaba Central", "Malaba North", "Malaba South", "Ang'urai South", "Ang'urai North", "Ang'urai East"], "Teso South": ["Amukura West", "Amukura East", "Amukura Central", "Chakoi", "Alupe"]},
    "Elgeyo-Marakwet": {"Keiyo North": ["Emsoo", "Kamariny", "Kapchemutwa", "Tambach"], "Keiyo South": ["Kaptarakwa", "Chepkorio", "Soy South", "Kabiemit", "Metkei"], "Marakwet East": ["Kapyego", "Sambirir", "Endo", "Embobut / Embolot"], "Marakwet West": ["Lelan", "Sengwer", "Cherang'any/Chebororwa", "Moiben/Kuserwo", "Kapsowar", "Arror"]},
    "Embu": {"Manyatta": ["Ruguru/Ngandori", "Kithimu", "Nginda", "Mbeti North", "Kirimari", "Gaturi South"], "Mbeere North": ["Nthawa", "Muminji", "Evurore"], "Mbeere South": ["Mwea", "Makima", "Mbeti South", "Mavuria", "Kiambere"], "Runyenjes": ["Gaturi North", "Kagaari South", "Kagaari North", "Central", "Kyeni North", "Kyeni South"]},
    "Garissa": {"Daadab": ["Dertu", "Dadaab", "Labasigale", "Damajale", "Liboi", "Abakaile"], "Fafi": ["Bura", "Dekaharia", "Jarajila", "Fafi", "Nanighi"], "Garissa Township": ["Waberi", "Galbet", "Township", "Iftin"], "Hulugho": ["Hulugho", "Sangailu", "Ijara", "Masalani"], "Ijara": ["Hulugho", "Sangailu", "Ijara", "Masalani"], "Lagdera": ["Modogashe", "Benane", "Goreale", "Maalamin", "Sabena", "Baraki"], "Balambala": ["Balambala", "Danyere", "Jara Jara", "Saka", "Sankuri"]},
    "Homa Bay": {"Homa Bay Town": ["Homa Bay Central", "Homa Bay Arujo", "Homa Bay West", "Homa Bay East"], "Kabondo Kasipul": ["Kabondo East", "Kabondo West", "Kokwanyo/Kakelo", "Kojwach"], "Karachuonyo": ["West Karachuonyo", "Kanyaluo", "Central Karachuonyo", "Kibiri", "North Karachuonyo"], "Kasipul": ["West Kasipul", "South Kasipul", "Central Kasipul", "East Kamagak", "West Kamagak"], "Mbita": ["Mfangano Island", "Rusinga Island", "Kasgunga", "Gembe", "Lambwe"], "Ndhiwa": ["Kwabwai", "Kanyidoto", "Kanyikela", "Riana", "Kabuoch North", "Kabuoch South/Pala"], "Rangwe": ["West Gem", "East Gem", "Kagan", "Kochia"], "Suba": ["Gwassi South", "Gwassi North", "Kaksingri West", "Ruma Kaksingri"]},
    "Isiolo": {"Isiolo North": ["Wabera", "Bulla Pesa", "Chari", "Cherab", "Ngaremara", "Burat", "Oldo/Nyiro"], "Isiolo South": ["Garbatulla", "Kinnna", "Sericho"]},
    "Kakamega": {"Butere": ["Marama West", "Marama Central", "Marenyo - Shianda", "Marama North", "Marama South"], "Kakamega Central": ["Sheywe", "Mahiakalo", "Shirere"], "Khwisero": ["Kisa North", "Kisa East", "Kisa West", "Kisa Central"], "Lugari": ["Mautuma", "Lugari", "Lumakanda", "Chekalini", "Chevaywa", "Lwandeti"], "Lurambi": ["Butsotso East", "Butsotso South", "Butsotso Central", "Sheywe", "Mahiakalo", "Shirere"], "Malava": ["West Kabras", "Chemuche", "East Kabras", "South Kabras", "Manda-Shivanga", "Shirugu-Mugai"], "Matungu": ["Koyonzo", "Kholera", "Khalaba", "Mayoni", "Namamali"], "Mumias East": ["Lusheya/Lubinu", "Malaha/Isongo/Makunga", "East Wanga"], "Mumias West": ["Mumias Central", "Mumias North", "Etenje", "Musanda"], "Navakholo": ["Ingotse-Mathia", "Shinoyi-Shikomari-Esumeyia", "Bunyala West", "Bunyala East", "Bunyala Central"], "Shinyalu": ["Isukha North", "Isukha Central", "Isukha South", "Isukha East", "Isukha West", "Murhanda"], "Ikolomani": ["Idakho South", "Idakho East", "Idakho North", "Idakho Central"]},
    "Kericho": {"Ainamoi": ["Kapsoit", "Ainamoi", "Kipchimchim", "Kapsaos", "Kipchebor", "Kapkugerwet"], "Belgut": ["Waldai", "Kabianga", "Cheptororiet/Seretut", "Chaik", "Kapsuser"], "Bureti": ["Kisiara", "Tebesonik", "Cheboin", "Chemosot", "Litein", "Cheplanget", "Kapkatet"], "Kipkelion East": ["Londiani", "Kedowa/Kimugul", "Chepseon", "Tendeno/Sorget"], "Kipkelion West": ["Kunyak", "Kipkelion", "Chilchila", "Kamasian"], "Sigowet/Soin": ["Sigowet", "Kaplelartet", "Soliat", "Soin"]},
    "Kilifi": {"Ganze": ["Ganze", "Bamba", "Jaribuni", "Sokoke"], "Kaloleni": ["Kaloleni", "Kayafungo", "Mwanamwinga", "Mariakani"], "Kilifi North": ["Tezo", "Sokoni", "Kibarani", "Dabaso", "Matsangoni", "Watamu", "Mnarani"], "Kilifi South": ["Junju", "Mwarakaya", "Shimo la Tewa", "Chasimba", "Mtepeni"], "Magarini": ["Marafa", "Magarini", "Gongoni", "Adu", "Garashi", "Sabaki"], "Malindi": ["Jilore", "Kakuyuni", "Ganda", "Malindi Town", "Shella"], "Rabai": ["Mwawesa", "Ruruma", "Kambe/Ribe", "Rabai/Kisurutini"]},
    "Kirinyaga": {"Kirinyaga Central": ["Mutira", "Kanyekini", "Kerugoya", "Inoi"], "Gichugu": ["Kabare", "Baragwi", "Njukiini", "Ngariama", "Karumandi"], "Ndia": ["Mukure", "Kiine", "Kariti"], "Mwea": ["Mutithi", "Kangai", "Wamumu", "Nyangati", "Murinduko", "Gathigiriri", "Teberia"]},
    "Kisii": {"Bobasi": ["Masige West", "Masige East", "Bobasi Central", "Nyacheki", "Bassi Bogetaorio", "Bobasi Chache", "Sameta/Mokwerero", "Bobasi Boitangare"], "Bonchari": ["Bomariba", "Bogiakumu", "Bomorenda", "Riana"], "Kitutu Chache North": ["Monyerero", "Sensi", "Marani", "Kegogi"], "Kitutu Chache South": ["Bogusero", "Bogeka", "Nyakoe", "Kitutu Central", "Nyatieko"], "Nyaribari Chache": ["Bobaracho", "Kisii Central", "Keumbu", "Kiogoro", "Ibeno"], "Nyaribari Masaba": ["Ichuni", "Nyamasibi", "Masimba", "Gesusu", "Kiamokama"], "South Mugirango": ["Bogetenga", "Borabu / Chitago", "Moticho", "Getenga", "Tabaka", "Boikanga"], "Bomachoge Borabu": ["Bombaba Borabu", "Boochi Borabu", "Bokimonge", "Magenche"], "Bomachoge Chache": ["Majoge Basi", "Boochi / Tendere", "Bosoti / Sengera"]},
    "Kitui": {"Kitui Central": ["Miambani", "Township", "Kyangwithya West", "Mulango", "Kyangwithya East"], "Kitui East": ["Zombe/Mwitika", "Chuluni", "Nzambani", "Voo/Kyamatu", "Endau/Malalani", "Mutito/Kaliku"], "Kitui Rural": ["Kisasi", "Mbitini", "Kwavonza/Yatta", "Kanyangi"], "Kitui South": ["Ikanga/Kyatune", "Mutomo", "Mutha", "Ikutha", "Kanziko", "Athi"], "Kitui West": ["Mutonguni", "Kauwi", "Matinyani", "Kwa Mutonga/Kithumula"], "Mwingi Central": ["Kivou", "Nguni", "Mwingi Central", "Waita", "Mwingi North", "Kavuvuu/Thitani"], "Mwingi North": ["Ngomeni", "Kyuso", "Mumoni", "Tseikuru", "Tharaka"], "Mwingi West": ["Kyome/Thaana", "Nguutani", "Migwani", "Kiomo/Kyethani"]},
    "Kwale": {"Kinango": ["Ndavaya", "Puma", "Kinango", "Mackinnon Road", "Chengoni/Samburu", "Mwavumbo", "Kasemeni"], "Lunga Lunga": ["Pongwe/Kikoneni", "Dzombo", "Mwereni", "Vanga"], "Matuga": ["Tsimba Golini", "Waa", "Tiwi", "Kubo South", "Mkongani"], "Msambweni": ["Gombato Bongwe", "Ukunda", "Kinondo", "Ramisi"]},
    "Laikipia": {"Laikipia East": ["Ngobit", "Tigithi", "Thingithu", "Nanyuki", "Umande"], "Laikipia North": ["Sosian", "Segera", "Mugogodo West", "Mugogodo East"], "Laikipia West": ["Ol-Moran", "Rumuruti Township", "Githiga", "Marmanet", "Igwamiti", "Salama"]},
    "Lamu": {"Lamu East": ["Faza", "Kiunga", "Basuba"], "Lamu West": ["Shella", "Mkomani", "Hindi", "Mkunumbi", "Hongwe", "Witu", "Bahari"]},
    "Mandera": {"Banissa": ["Banissa", "Derkhale", "Guba", "Malkamari", "Kiliwehiri"], "Lafey": ["Sala", "Fino", "Lafey", "Waranqara", "Alango Arba"], "Mandera East": ["Arabia", "Bulla Mpya", "Khalalio", "Neboi", "Township"], "Mandera North": ["Ashabito", "Guticha", "Marothile", "Rhamu", "Rhamu Dimtu"], "Mandera South": ["Wargadud", "Kutulo", "Elwak South", "Elwak North", "Shimbir Fatuma"], "Mandera West": ["Takaba South", "Takaba", "Lagsure", "Dandu", "Gither"]},
    "Marsabit": {"Laisamis": ["Loiyangalani", "Kargi/South Horr", "Korr/Ngurunit", "Logo Logo", "Laisamis"], "Moyale": ["Butiye", "Sololo", "Heillu/Manyatta", "Golbo", "Moyale Township", "Uran", "Obbu"], "North Horr": ["Dukana", "North Horr", "Illeret", "Turbi", "Maikona"], "Saku": ["Sagante/Jaldesa", "Karare", "Marsabit Central"]},
    "Meru": {"Buuri": ["Timau", "Kisima", "Kiirua/Nkando", "Ruiri/Rwarera", "Kibirichia"], "Central Imenti": ["Mwanganthia", "Abothuguchi Central", "Abothuguchi West", "Kiagu", "Kithirune"], "Igembe Central": ["Akirang'ondu", "Athiru Saitoti", "Njia", "Kangeta", "Igembe East"], "Igembe North": ["Antuambui", "Ntunene", "Antubetwe Kiongo", "Naathu", "Amwathi"], "Igembe South": ["Maua", "Kegoi/Antubochiu", "Athiru Gaiti", "Akachiu", "Kanuni"], "North Imenti": ["Municipality", "Ntima East", "Ntima West", "Nyaki West", "Nyaki East"], "South Imenti": ["Mitunguu", "Igoji East", "Igoji West", "Abogeta East", "Abogeta West", "Nkuene"], "Tigania Central": ["Miumbine", "Mikinduri", "Kiguchwa", "Muthara"], "Tigania East": ["Thangatha", "Mikinduri", "Kiguchwa", "Muthara", "Karama"], "Tigania West": ["Athwana", "Akithi", "Kianjai", "Nkomo", "Mbeu"]},
    "Migori": {"Awendo": ["North Sakwa", "South Sakwa", "West Sakwa", "Central Sakwa"], "Kuria East": ["Gokeharaka/Getambwega", "Ntimaru West", "Ntimaru East", "Nyabasi East", "Nyabasi West"], "Kuria West": ["Bukira East", "Bukira Centrl/Ikerege", "Isibania", "Makarang'e", "Tagare", "Nyamosense/Komosoko"], "Nyatike": ["Kachieng'", "Kanyasa", "North Kadem", "Macalder/Kanyarwanda", "Kaler", "Got Kachola", "Muhuru"], "Rongo": ["North Kamagambo", "Central Kamagambo", "East Kamagambo", "South Kamagambo"], "Suna East": ["God Jope", "Suna Central", "Kakrao", "Kwa"], "Suna West": ["Wiga", "Wasweta II", "Ragana-Oruba", "Wasimbete"], "Uriri": ["West Kanyamkago", "North Kanyamkago", "Central Kanyamkago", "South Kanyamkago", "East Kanyamkago"]},
    "Nandi": {"Aldai": ["Kabwareng", "Terik", "Kemeloi-Maraba", "Kobujoi", "Kaptumo-Kaboi", "Koyo-Ndurio"], "Chesumei": ["Rongai", "Chemundu/Kapng'etuny", "Kosirai", "Lelmokwo/Ngechek", "Kaptel/Kamoiywo"], "Emgwen": ["Chepkumia", "Kapkangani", "Kapsabet", "Kilibwoni"], "Mosop": ["Chepterwai", "Kipkaren", "Kurgung/Surungai", "Kabiyet", "Nd通话", "Kabisaga", "Sangalo/Kebulonik"], "Nandi Hills": ["Nandi Hills", "Chepkunyuk", "Ollessos", "Kapchorua"], "Tindiret": ["Songhor/Soba", "Tindiret", "Chemelil/Chemase", "Kapsimotwo"]},
    "Narok": {"Narok East": ["Mosiro", "Ildamat", "Keekonyokie", "Suswa"], "Narok North": ["Olpusimoru", "Olorropil", "Nkareta", "Olkiriane", "Melili", "Township"], "Narok South": ["Majimoto/Naroosura", "Ololulung'a", "Melelo", "Loita", "Sogoo", "Sagamian"], "Narok West": ["Ilmotiok", "Mara", "Siana", "Naikarra"], "Kilgoris": ["Kilgoris Central", "Keyian", "Angata Barikoi", "Shankoe", "Kimintet", "Lolgorian"], "Emurua Dikirr": ["Ilkerin", "Ololmasani", "Mogondo", "Kapsasian"]},
    "Nyamira": {"Borabu": ["Mekenene", "Kiabonyoru", "Esise", "Nyansiongo"], "Kitutu Masaba": ["Rigoma", "Gachuba", "Kemera", "Magombo", "Manga", "Gesima"], "North Mugirango": ["Itibo", "Bomwagamo", "Bokeira", "Magwagwa", "Ekerenyo"], "West Mugirango": ["Nyamaiya", "Bogichora", "Bosamaro", "Bonyamatuta", "Township"]},
    "Nyandarua": {"Kinangop": ["Engineer", "Gathara", "North Kinangop", "Murungaru", "Njabini/Kiburu", "Nyakio", "Magumu", "Githabai"], "Kipipiri": ["Wanjohi", "Kipipiri", "Geta", "Githioro"], "Ndaragwa": ["Leshau/Pondo", "Kiriita", "Central", "Shamata"], "Ol Joro Orok": ["Gathanji", "Gatimu", "Weru", "Charagita"], "Ol Kalou": ["Karau", "Kanjuiri Ridge", "Mirangine", "Kaimbaga", "Rurii"]},
    "Samburu": {"Samburu East": ["Waso", "Wamba West", "Wamba East", "Wamba North"], "Samburu North": ["El-Barta", "Nachola", "Ndoto", "Nyiro", "Angata Nanyokie", "Baawa"], "Samburu West": ["Lodokejek", "Suguta Marmar", "Maralal", "Loosuk", "Poro"]},
    "Siaya": {"Alego Usonga": ["Usonga", "West Alego", "Central Alego", "Siaya Township", "North Alego", "South East Alego"], "Bondo": ["West Yimbo", "Central Sakwa", "South Sakwa", "Yimbo East", "West Sakwa", "North Sakwa"], "Gem": ["North Gem", "West Gem", "Central Gem", "Yala Township", "East Gem", "South Gem"], "Rarieda": ["East Asembo", "West Asembo", "North Uyoma", "South Uyoma", "West Uyoma"], "Ugenya": ["West Ugenya", "Ukwala", "North Ugenya", "East Ugenya"], "Ugunja": ["Sidindi", "Sigomere", "Ugunja"]},
    "Taita-Taveta": {"Mwatate": ["Rong'e", "Mwatate", "Bura", "Chawia", "Wusi/Kishamba"], "Taveta": ["Chala", "Mahoo", "Bomeni", "Mata", "Mboghoni"], "Voi": ["Mbololo", "Sagalla", "Kaloleni", "Marungu", "Kasigau", "Ngolia"], "Wundanyi": ["Wundanyi/Mbale", "Werugha", "Wumingu/Kishushe", "Mwanda/Mgange"]},
    "Tana River": {"Bura": ["Chewani", "Madogo", "Bangale", "Sala", "Nanighi"], "Galole": ["Wayu", "Mikinduni", "Chewani", "Kinakomba", "Gwano"], "Garsen": ["Kipini East", "Garsen South", "Kipini West", "Garsen Central", "Garsen West", "Garsen North"]},
    "Tharaka-Nithi": {"Chuka/Igambang'ombe": ["Mariani", "Karingani", "Magumoni", "Mugwe", "Igambang'ombe"], "Maara": ["Mitheru", "Muthambi", "Mwimbi", "Ganga", "Chogoria"], "Tharaka": ["Gatunga", "Mukothima", "Nkondi", "Chiakariga", "Marimanti"]},
    "Trans-Nzoia": {"Cherangany": ["Sitatunga", "Makutano", "Kaplamai", "Motosiet", "Cherangany/Suwerwa", "Chepsiro/Kiptoror", "Sinyerere"], "Endebess": ["Endebess", "Matumbei", "Chepchoina"], "Kiminini": ["Kiminini", "Waitaluk", "Sirende", "Hospital", "Sikhendu", "Nabwiswa"], "Kwanza": ["Kapomboi", "Kwanza", "Keiyo", "Bidii"], "Saboti": ["Kinyoro", "Matisi", "Tuwani", "Saboti", "Machewa"]},
    "Turkana": {"Turkana Central": ["Kerio Delta", "Kang'atotha", "Kalokol", "Lodwar Township", "Kanamkemer"], "Turkana East": ["Kapedo/Napeitom", "Katilia", "Lokori/Kochodin"], "Turkana North": ["Kaeris", "Lake Zone", "Lapur", "Kaaleng/Kaikor", "Kibish", "Napak"], "Turkana South": ["Lokichar", "Lobokat", "Kaputir", "Katilu", "Kalapata"], "Turkana West": ["Kakuma", "Lopur", "Letea", "Songot", "Kalobeyei", "Lokichoggio", "Nanaam"], "Loima": ["Kotaruk/Lobei", "Turkwel", "Loima", "Lokiriama/Lorengegicho"]},
    "Vihiga": {"Emuhaya": ["North East Bunyore", "Central Bunyore", "West Bunyore"], "Hamisi": ["Shiru", "Gisambai", "Shamakhokho", "Banja", "Muhudu", "Tambua", "Jepkoyai"], "Luanda": ["Luanda Township", "Wemilabi", "Mwibona", "Luanda South", "Emabungo"], "Sabatia": ["Lyaduywa/Izava", "West Sabatia", "Chavakali", "North Maragoli", "Wodanga", "Busali"], "Vihiga": ["Lugaga-Wamuluma", "South Maragoli", "Central Maragoli", "Mungoma"]},
    "Wajir": {"Eldas": ["Eldas", "Dellu", "Lakoley South/Basir", "Elnur/Tula Tula"], "Tarbaj": ["Elben", "Sarman", "Tarbaj", "Wargadud"], "Wajir East": ["Wagberi", "Township", "Barwago", "Khorof/Harar"], "Wajir North": ["Gurar", "Bute", "Korondile", "Malkagufu", "Batalu", "Danaba", "Godoma"], "Wajir South": ["Benane", "Burder", "Dadajabula", "Habasswein", "Lagboghol South", "Ibrahim Ure", "Diff"], "Wajir West": ["Arbajahan", "Hadado/Athibohol", "Ademasajida", "Ganyure/Wagalla"]},
    "West Pokot": {"Kapenguria": ["Riwo", "Kapenguria", "Mnagei", "Siyoi", "Endugh", "Sook"], "Kacheliba": ["Suam", "Kodich", "Kasei", "Kapchok", "Kiwawa", "Alale"], "Pokot South": ["Chepareria", "Batei", "Lelan", "Tapach"], "Sigor": ["Weiwei", "Masool", "Lomut", "Sekerr"]}
}
