# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encounters", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial Holistic Palliative Assessment"),
                            ("PAIN", "Comprehensive Pain Assessment (0-10 & Mapping)"),
                            ("FUNCTIONAL", "Functional Assessment (PPS & ECOG)"),
                            ("PSYCHOSOCIAL", "Psychosocial & Family Assessment"),
                            ("SPIRITUAL", "Spiritual & Existential Assessment"),
                            ("NUTRITIONAL", "Nutritional & Intake Assessment"),
                            ("CAREGIVER", "Caregiver Burden & Needs Assessment"),
                            ("FOLLOWUP", "Routine Clinical Follow-up Assessment"),
                        ],
                        db_index=True,
                        default="INITIAL",
                        max_length=30,
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "pain_score",
                    models.IntegerField(
                        blank=True, help_text="Numeric Rating Scale 0-10", null=True
                    ),
                ),
                (
                    "pps_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Palliative Performance Scale % (10-100)",
                        null=True,
                    ),
                ),
                (
                    "ecog_score",
                    models.IntegerField(
                        blank=True, help_text="ECOG Performance Status (0-4)", null=True
                    ),
                ),
                (
                    "structured_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured tool-specific observations",
                    ),
                ),
                (
                    "clinical_summary",
                    models.TextField(
                        help_text="Clinician impressions, diagnosis synthesis, management plan"
                    ),
                ),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Assessment",
                "verbose_name_plural": "Clinical Assessments",
                "ordering": ["-assessment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentAmendment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amended_at", models.DateTimeField(auto_now_add=True)),
                ("reason_for_amendment", models.TextField()),
                ("previous_content", models.TextField()),
                ("amended_notes", models.TextField()),
                (
                    "amended_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Amendment",
                "verbose_name_plural": "Assessment Amendments",
                "ordering": ["-amended_at"],
            },
        ),
    ]
