# Generated by Django 5.2.17 on 2026-08-23 10:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_assessment_assessment_patient_date_idx_and_more"),
        ("encounters", "0002_encounter_encounter_patient_date_idx"),
        ("patients", "0004_alter_patient_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="ecog_score",
            field=models.IntegerField(
                blank=True,
                help_text="ECOG Performance Status (0-4)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="pain_score",
            field=models.IntegerField(
                blank=True,
                help_text="Numeric Rating Scale 0-10",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="pps_score",
            field=models.IntegerField(
                blank=True,
                help_text="Palliative Performance Scale % (0-100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pain_score__isnull", True),
                    models.Q(("pain_score__gte", 0), ("pain_score__lte", 10)),
                    _connector="OR",
                ),
                name="assessment_pain_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pps_score__isnull", True),
                    models.Q(("pps_score__gte", 0), ("pps_score__lte", 100)),
                    _connector="OR",
                ),
                name="assessment_pps_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ecog_score__isnull", True),
                    models.Q(("ecog_score__gte", 0), ("ecog_score__lte", 4)),
                    _connector="OR",
                ),
                name="assessment_ecog_score_range",
            ),
        ),
    ]
