# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("REFERRAL_LETTER", "Referral Letter / Medical Transfer"),
                            ("CLINICAL_SUMMARY", "Hospital Summary / Discharge Notes"),
                            ("CONSENT_FORM", "Signed Consent / Advance Care Directive"),
                            ("LAB_REPORT", "Laboratory / Pathology Report"),
                            (
                                "RADIOLOGY_REPORT",
                                "Radiology / Imaging Report (CT, MRI, X-Ray)",
                            ),
                            ("PRESCRIPTION", "External Prescription / Pharmacy Order"),
                            ("OTHER", "Other Document"),
                        ],
                        default="REFERRAL_LETTER",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="clinical_documents/%Y/%m/")),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Document",
                "verbose_name_plural": "Patient Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
