# Generated by Django 5.2.17 on 2026-08-22 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_patientdocument_file"),
        ("patients", "0004_alter_patient_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="patientdocument",
            index=models.Index(
                fields=["patient", "uploaded_at"], name="doc_patient_uploaded_idx"
            ),
        ),
    ]
