# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encounters", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SymptomAssessmentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "total_distress_score",
                    models.IntegerField(
                        default=0, help_text="Cumulative ESAS distress score sum"
                    ),
                ),
                ("clinical_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="symptom_records",
                        to="encounters.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom_records",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_symptom_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Symptom Assessment Record",
                "verbose_name_plural": "Symptom Assessment Records",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="SymptomScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "symptom_type",
                    models.CharField(
                        choices=[
                            ("PAIN", "Pain"),
                            ("TIREDNESS", "Tiredness / Fatigue"),
                            ("DROWSINESS", "Drowsiness"),
                            ("NAUSEA", "Nausea"),
                            ("LACK_OF_APPETITE", "Lack of Appetite"),
                            ("SHORTNESS_OF_BREATH", "Shortness of Breath / Dyspnea"),
                            ("DEPRESSION", "Depression / Sadness"),
                            ("ANXIETY", "Anxiety / Nervousness"),
                            ("WELLBEING", "Overall Wellbeing"),
                            ("CONSTIPATION", "Constipation"),
                            ("INSOMNIA", "Insomnia / Sleep Difficulty"),
                            ("OTHER", "Other Symptom"),
                        ],
                        max_length=30,
                    ),
                ),
                ("custom_symptom_name", models.CharField(blank=True, max_length=100)),
                (
                    "score",
                    models.IntegerField(
                        help_text="0 (None) to 10 (Worst Possible)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="symptoms.symptomassessmentrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Symptom Score",
                "verbose_name_plural": "Symptom Scores",
                "ordering": ["record", "symptom_type"],
            },
        ),
    ]
