# Generated by Django 5.2.17 on 2026-08-22 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0002_encounter_encounter_patient_date_idx"),
        ("patients", "0004_alter_patient_photo"),
        ("symptoms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="symptomassessmentrecord",
            index=models.Index(
                fields=["patient", "recorded_at"], name="symptom_patient_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="symptomscore",
            constraint=models.UniqueConstraint(
                fields=("record", "symptom_type"), name="unique_symptom_per_record"
            ),
        ),
    ]
