# Generated by Django 5.2.17 on 2026-08-23 10:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0002_encounter_encounter_patient_date_idx"),
        ("patients", "0004_alter_patient_photo"),
        ("symptoms", "0002_symptomassessmentrecord_symptom_patient_date_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="symptomassessmentrecord",
            name="total_distress_score",
            field=models.IntegerField(
                default=0,
                help_text="Cumulative ESAS distress score sum (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="symptomassessmentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_distress_score__gte", 0), ("total_distress_score__lte", 100)
                ),
                name="symptom_total_distress_range",
            ),
        ),
    ]
