# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("care", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("CLINIC_VISIT", "Hospice Clinic Consultation"),
                            ("HOME_VISIT", "Home Care Visit"),
                            ("TELEPHONE", "Telephone Follow-up / Teleconsultation"),
                            ("COMMUNITY_VISIT", "Community / Outreach Visit"),
                            ("COUNSELLING", "Psychosocial / Bereavement Session"),
                            ("MDT_REVIEW", "Multidisciplinary Team Case Review"),
                            ("DAY_CARE", "Hospice Day Care Activity"),
                            ("OTHER", "Other Encounter"),
                        ],
                        db_index=True,
                        default="CLINIC_VISIT",
                        max_length=30,
                    ),
                ),
                (
                    "encounter_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(default="Nairobi Hospice Clinic", max_length=255),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Reason for encounter, e.g. Severe pain exacerbation, routine home check",
                        max_length=255,
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(
                        help_text="Clinical summary / Progress notes (SOAP / Narrative)"
                    ),
                ),
                (
                    "interventions_performed",
                    models.TextField(
                        blank=True,
                        help_text="Procedures, med administration, wound dressing, education, counseling",
                    ),
                ),
                ("next_followup_date", models.DateField(blank=True, null=True)),
                ("next_followup_plan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encounters",
                        to="care.episodeofcare",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Encounter",
                "verbose_name_plural": "Encounters",
                "ordering": ["-encounter_date", "-created_at"],
            },
        ),
    ]
