# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Individualized Palliative Care Plan", max_length=200
                    ),
                ),
                ("primary_diagnosis", models.CharField(blank=True, max_length=255)),
                (
                    "overall_goals",
                    models.TextField(
                        help_text="Patient-centred priorities and overarching goals of care"
                    ),
                ),
                (
                    "resuscitation_preference",
                    models.CharField(
                        default="Allow Natural Death (AND) / Comfort Measures",
                        help_text="Advance care directive preference",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active Care Plan"),
                            ("UNDER_REVIEW", "Under Multidisciplinary Review"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Discontinued / Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "review_date",
                    models.DateField(
                        blank=True,
                        help_text="Next multidisciplinary review date",
                        null=True,
                    ),
                ),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_care_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_plans",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Care Plan",
                "verbose_name_plural": "Care Plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarePlanNeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physical / Symptom Burden"),
                            ("PSYCHOSOCIAL", "Psychosocial & Family"),
                            ("SPIRITUAL", "Spiritual & Existential"),
                            ("PRACTICAL", "Practical & Financial"),
                            ("ETHICAL", "Advance Care Planning & Ethical"),
                        ],
                        default="PHYSICAL",
                        max_length=20,
                    ),
                ),
                (
                    "problem_description",
                    models.TextField(help_text="Identified issue or symptom"),
                ),
                (
                    "goal",
                    models.TextField(
                        help_text="Desired measurable or subjective outcome"
                    ),
                ),
                (
                    "interventions",
                    models.TextField(
                        help_text="Action steps and clinical interventions"
                    ),
                ),
                (
                    "responsible_discipline",
                    models.CharField(default="Nursing & Medical", max_length=100),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("outcome_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "care_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="needs",
                        to="care.careplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Care Plan Need / Goal",
                "verbose_name_plural": "Care Plan Needs & Goals",
                "ordering": ["is_resolved", "category", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EpisodeOfCare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reason_for_admission", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Palliative Episode"),
                            ("INACTIVE", "Inactive / Suspended"),
                            ("DISCHARGED", "Discharged"),
                            ("DECEASED", "Deceased"),
                            ("TRANSFERRED", "Transferred to Other Hospice/Hospital"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("discharge_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_episodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode of Care",
                "verbose_name_plural": "Episodes of Care",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CareTeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRIMARY_DOCTOR", "Primary Palliative Doctor"),
                            ("PRIMARY_NURSE", "Primary Palliative Nurse"),
                            ("CLINICAL_OFFICER", "Clinical Officer"),
                            ("SOCIAL_WORKER", "Social Worker"),
                            ("COUNSELLOR", "Psychological Counsellor"),
                            ("PHARMACIST", "Pharmacist"),
                            ("PHYSIOTHERAPIST", "Physiotherapist"),
                            ("NUTRITIONIST", "Nutritionist"),
                            ("SPIRITUAL_COUNSELLOR", "Spiritual / Pastoral Leader"),
                            ("COMMUNITY_WORKER", "Community Health Promoter"),
                            ("CARE_COORDINATOR", "Care Coordinator"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_assignments",
                        to="accounts.staffprofile",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="care.episodeofcare",
                    ),
                ),
            ],
            options={
                "verbose_name": "Care Team Member",
                "verbose_name_plural": "Care Team Members",
                "ordering": ["role", "staff_member__user__first_name"],
            },
        ),
        migrations.AddField(
            model_name="careplan",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="care_plans",
                to="care.episodeofcare",
            ),
        ),
    ]
