# Generated by Django 5.2.17 on 2026-08-22 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_mfa_fields"),
        ("care", "0001_initial"),
        ("patients", "0004_alter_patient_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="careplan",
            index=models.Index(
                fields=["patient", "status"], name="careplan_patient_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="careteammember",
            index=models.Index(
                fields=["episode", "staff_member"], name="team_episode_staff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episodeofcare",
            index=models.Index(
                fields=["patient", "status"], name="episode_patient_status_idx"
            ),
        ),
    ]
