# Generated by Django 5.2.17 on 2026-08-24 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0002_careplan_careplan_patient_status_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalAdvice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("procedure", models.CharField(db_index=True, max_length=150)),
                ("heading", models.CharField(blank=True, max_length=200)),
                ("advice_text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        default="Procedural Care & Patient Advice", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clinical Advice Guide",
                "verbose_name_plural": "Clinical Advice Guides",
                "ordering": ["procedure"],
            },
        ),
    ]
