# Generated by Django 5.1.15 on 2026-08-21 05:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ESSENTIAL_MEDICINE", "Essential Palliative Medications"),
                            (
                                "CONTROLLED_OPIOID",
                                "Controlled Opioids (Oral Morphine / Fentanyl)",
                            ),
                            ("WOUND_CARE", "Palliative Wound Care & Dressings"),
                            ("PPE_SANITATION", "Infection Control & PPE"),
                            ("NUTRITIONAL_FEED", "Enteral & Nutritional Supplements"),
                            ("DIAGNOSTIC", "Diagnostic & Lab Reagents"),
                        ],
                        db_index=True,
                        default="ESSENTIAL_MEDICINE",
                        max_length=30,
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        default="Units",
                        help_text="e.g. Bottles, Boxes, Packs, Vials",
                        max_length=50,
                    ),
                ),
                ("quantity_on_hand", models.IntegerField(default=0)),
                ("minimum_reorder_level", models.IntegerField(default=10)),
                (
                    "unit_cost_kes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Unit Cost (KES)",
                    ),
                ),
                (
                    "location_bin",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Pharmacy Main Rack A3, Cold Storage 2",
                        max_length=100,
                    ),
                ),
                ("is_controlled_substance", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stock Item",
                "verbose_name_plural": "Stock Items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PHARMACEUTICAL", "Pharmaceutical & Essential Meds"),
                            ("CONSUMABLES", "Medical Consumables & Wound Care"),
                            ("OXYGEN_EQUIPMENT", "Oxygen & Medical Equipment"),
                            ("PPE_SANITATION", "Infection Control & PPE"),
                            ("NUTRITION", "Clinical Nutrition & Supplements"),
                            ("GENERAL_SERVICES", "Facility, Logistics & IT Services"),
                        ],
                        default="PHARMACEUTICAL",
                        max_length=30,
                    ),
                ),
                ("contact_person", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "kra_pin",
                    models.CharField(blank=True, max_length=50, verbose_name="KRA PIN"),
                ),
                ("physical_address", models.TextField(blank=True)),
                (
                    "payment_terms",
                    models.CharField(default="30 Days Net", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Supplier"),
                            ("PREFERRED", "Preferred Hospice Partner"),
                            ("UNDER_REVIEW", "Under Review / Audit"),
                            ("INACTIVE", "Inactive / Suspended"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "po_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "order_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft Requisition"),
                            ("PENDING_APPROVAL", "Pending Management Approval"),
                            ("APPROVED", "Approved & Issued to Vendor"),
                            ("PARTIALLY_DELIVERED", "Partially Delivered"),
                            ("COMPLETED", "Completed / In Stock"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="APPROVED",
                        max_length=30,
                    ),
                ),
                (
                    "total_amount_kes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Total Amount (KES)",
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_orders",
                        to="operations.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement Order",
                "verbose_name_plural": "Procurement Orders",
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_requested", models.IntegerField(default=1)),
                ("quantity_received", models.IntegerField(default=0)),
                (
                    "unit_price_kes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_price_kes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="operations.procurementorder",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="operations.stockitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procurement Order Item",
                "verbose_name_plural": "Procurement Order Items",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "Stock Received (PO Delivery)"),
                            ("DISPENSE", "Dispensed to Patient"),
                            ("TRANSFER", "Transfer to Home Care Kits"),
                            ("ADJUSTMENT", "Physical Count Audit Adjustment"),
                            ("WASTAGE", "Wastage / Expired / Damaged"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive for inbound, negative for outbound"
                    ),
                ),
                ("balance_after", models.IntegerField()),
                (
                    "reference_document",
                    models.CharField(
                        blank=True,
                        help_text="e.g. PO Number, Patient ID, or Audit ID",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="operations.stockitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stockitem",
            name="preferred_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_items",
                to="operations.vendor",
            ),
        ),
    ]
