# Generated by Django 5.1.15 on 2026-08-21 06:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
        ("patients", "0003_patient_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("ESSENTIAL_MEDICINE", "Essential Palliative Medications"),
                    (
                        "CONTROLLED_OPIOID",
                        "Controlled Opioids (Oral Morphine / Fentanyl)",
                    ),
                    ("WOUND_CARE", "Palliative Wound Care & Dressings"),
                    ("OXYGEN_EQUIPMENT", "Oxygen & Medical Equipment"),
                    ("PPE_SANITATION", "Infection Control & PPE"),
                    ("NUTRITIONAL_FEED", "Enteral & Nutritional Supplements"),
                    ("DIAGNOSTIC", "Diagnostic & Lab Reagents"),
                ],
                db_index=True,
                default="ESSENTIAL_MEDICINE",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            (
                                "SUPPLIER_PURCHASE",
                                "Supplier / Vendor Purchase Invoice (Payable)",
                            ),
                            (
                                "PATIENT_SERVICE",
                                "Patient Clinical & Pharmacy Invoice (Receivable)",
                            ),
                            (
                                "DONOR_SUBSIDY",
                                "Institutional Donor / Subsidy Requisition",
                            ),
                        ],
                        db_index=True,
                        default="SUPPLIER_PURCHASE",
                        max_length=30,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft Invoice"),
                            ("ISSUED", "Issued / Awaiting Payment"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid & Reconciled"),
                            ("CANCELLED", "Cancelled / Void"),
                        ],
                        db_index=True,
                        default="ISSUED",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal_amount_kes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "tax_amount_kes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "discount_amount_kes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_amount_kes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "amount_paid_kes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, default="Bank Transfer (EFT / RTGS)", max_length=100
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="patients.patient",
                    ),
                ),
                (
                    "procurement_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="operations.procurementorder",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="operations.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "unit_price_kes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_price_kes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="operations.invoice",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_items",
                        to="operations.stockitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line Item",
                "verbose_name_plural": "Invoice Line Items",
            },
        ),
    ]
