# Generated by Django 5.1.15 on 2026-08-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_alter_stockitem_category_invoice_invoicelineitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Bank Transfer (EFT / RTGS)", "Bank Transfer (EFT / RTGS)"),
                    ("M-PESA (Paybill 981234)", "M-PESA (Paybill 981234)"),
                    ("Cheque", "Cheque"),
                    ("NHIF / SHA / Insurance", "NHIF / SHA / Insurance"),
                ],
                default="Cash",
                max_length=100,
            ),
        ),
    ]
