from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('operations', '0004_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(
                condition=models.Q(quantity_on_hand__gte=0),
                name='stock_quantity_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(
                condition=models.Q(minimum_reorder_level__gte=0),
                name='stock_reorder_level_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(
                condition=models.Q(unit_cost_kes__gte=0),
                name='stock_unit_cost_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(
                condition=~models.Q(quantity=0),
                name='movement_quantity_nonzero',
            ),
        ),
        migrations.AddConstraint(
            model_name='procurementorderitem',
            constraint=models.CheckConstraint(
                condition=models.Q(quantity_requested__gt=0),
                name='po_item_requested_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='procurementorderitem',
            constraint=models.CheckConstraint(
                condition=models.Q(quantity_received__gte=0),
                name='po_item_received_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='procurementorderitem',
            constraint=models.CheckConstraint(
                condition=models.Q(quantity_received__lte=models.F('quantity_requested')),
                name='po_item_received_not_over_requested',
            ),
        ),
        migrations.AddConstraint(
            model_name='procurementorderitem',
            constraint=models.CheckConstraint(
                condition=models.Q(unit_price_kes__gte=0),
                name='po_item_unit_price_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='procurementorderitem',
            constraint=models.CheckConstraint(
                condition=models.Q(total_price_kes__gte=0),
                name='po_item_total_price_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(subtotal_amount_kes__gte=0),
                name='invoice_subtotal_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(tax_amount_kes__gte=0),
                name='invoice_tax_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(discount_amount_kes__gte=0),
                name='invoice_discount_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(total_amount_kes__gte=0),
                name='invoice_total_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(amount_paid_kes__gte=0),
                name='invoice_paid_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(
                condition=models.Q(quantity__gt=0),
                name='invoice_line_quantity_positive',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(
                condition=models.Q(unit_price_kes__gte=0),
                name='invoice_line_unit_price_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(
                condition=models.Q(total_price_kes__gte=0),
                name='invoice_line_total_non_negative',
            ),
        ),
    ]
