# Generated by Django 5.2.17 on 2026-08-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_financial_integrity_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("prefix", models.CharField(max_length=3)),
                ("next_number", models.PositiveIntegerField(default=1)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "prefix"),
                        name="invoice_sequence_year_prefix_unique",
                    )
                ],
            },
        ),
    ]
