# Generated by Django 5.2.17 on 2026-08-24 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_invoicenumbersequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurementorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft Requisition"),
                    ("PENDING_APPROVAL", "Pending Management Approval"),
                    ("APPROVED", "Approved & Issued to Vendor"),
                    ("PARTIALLY_DELIVERED", "Partially Delivered"),
                    ("COMPLETED", "Completed / In Stock"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING_APPROVAL",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="procurementorder",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procurement_orders",
                to="operations.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="procurementorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="operations.procurementorder",
            ),
        ),
        migrations.AlterField(
            model_name="procurementorderitem",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="operations.stockitem",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="stock_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="operations.stockitem",
            ),
        ),
    ]
