# Generated by Django 5.2.17 on 2026-08-25 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0002_medicationstatement_med_patient_status_idx"),
        ("operations", "0010_appointmentdeletionrequest"),
        ("patients", "0006_patient_closure_date_patient_file_closed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="medication_statement",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked medication prescription/statement if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="medications.medicationstatement",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked patient record for dispensed medications/supplies",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
