# Generated by Django 5.2.17 on 2026-08-25 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0002_medicationstatement_med_patient_status_idx"),
        ("operations", "0011_stockmovement_medication_statement_and_more"),
        ("patients", "0006_patient_closure_date_patient_file_closed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentdeletionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Operations Approval"),
                    ("APPROVED", "Approved & Closed / Archived"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="patientdeletionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Operations Approval"),
                    ("APPROVED", "Approved & Closed / Archived"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("movement_type", "DISPENSE"), _negated=True),
                    models.Q(
                        ("patient__isnull", False),
                        ("medication_statement__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="dispense_requires_patient_and_rx",
            ),
        ),
    ]
