# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hospice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique Nairobi Hospice Identifier, e.g. NH-2026-0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("is_approximate_dob", models.BooleanField(default=False)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("F", "Female"),
                            ("M", "Male"),
                            ("O", "Other"),
                            ("U", "Unknown"),
                        ],
                        default="F",
                        max_length=2,
                    ),
                ),
                (
                    "identification_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL_ID", "National ID (Kenya)"),
                            ("PASSPORT", "Passport"),
                            ("BIRTH_CERT", "Birth Certificate"),
                            ("ALIEN_ID", "Alien ID"),
                            ("MILITARY_ID", "Military ID"),
                            ("NONE", "None / Not Available"),
                        ],
                        default="NATIONAL_ID",
                        max_length=30,
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("alternative_phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="Estate / Village / Road", max_length=255
                    ),
                ),
                ("county", models.CharField(default="Nairobi", max_length=100)),
                ("sub_county", models.CharField(blank=True, max_length=100)),
                (
                    "landmark",
                    models.CharField(
                        blank=True,
                        help_text="Notable landmark for home visit navigation",
                        max_length=255,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(default="English", max_length=50),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("WIDOWED", "Widowed"),
                            ("DIVORCED", "Divorced"),
                            ("SEPARATED", "Separated"),
                            ("OTHER", "Other"),
                        ],
                        default="MARRIED",
                        max_length=20,
                    ),
                ),
                ("religion", models.CharField(blank=True, max_length=100)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                (
                    "primary_diagnosis",
                    models.CharField(
                        blank=True,
                        help_text="Main palliative diagnosis, e.g., Cervical Ca Stage IV, ESRD",
                        max_length=255,
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Known medication, food, or latex allergies",
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Care"),
                            ("INACTIVE", "Inactive / On Hold"),
                            ("DISCHARGED", "Discharged"),
                            ("DECEASED", "Deceased"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("date_of_death", models.DateField(blank=True, null=True)),
                (
                    "place_of_death",
                    models.CharField(
                        blank=True,
                        help_text="Home, Hospital, Hospice Ward, etc.",
                        max_length=150,
                    ),
                ),
                ("cause_of_death", models.TextField(blank=True)),
                ("discharge_date", models.DateField(blank=True, null=True)),
                ("discharge_reason", models.TextField(blank=True)),
                (
                    "clinical_alerts",
                    models.TextField(
                        blank=True,
                        help_text="High-priority flags, e.g. Fall Risk, Severe Pain, High DNR Alert",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-registration_date", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="NextOfKin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "relationship",
                    models.CharField(
                        help_text="Spouse, Child, Sibling, Parent, Guardian, etc.",
                        max_length=100,
                    ),
                ),
                ("phone_number", models.CharField(max_length=30)),
                ("alternative_phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_of_kin",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Next of Kin",
                "verbose_name_plural": "Next of Kin",
            },
        ),
        migrations.CreateModel(
            name="Caregiver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("relationship", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Full-time, Nights, Weekends",
                        max_length=100,
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregivers",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caregiver",
                "verbose_name_plural": "Caregivers",
            },
        ),
    ]
