# Generated by Django 5.1.15 on 2026-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="ward",
            field=models.CharField(
                blank=True, help_text="Administrative / Electoral Ward", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Estate / Village / Road / House Number",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="landmark",
            field=models.CharField(
                blank=True,
                help_text="Closest Bus Stop / Matatu Stage / Landmark for home visits",
                max_length=255,
            ),
        ),
    ]
