# Generated by Django 5.1.15 on 2026-08-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_ward_alter_patient_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Patient identification photograph",
                null=True,
                upload_to="patients/photos/",
            ),
        ),
    ]
