# Generated by Django 5.2.17 on 2026-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_alter_patient_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Age"),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="caregiver_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Caregiver Number"
            ),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="gender",
            field=models.CharField(blank=True, max_length=20, verbose_name="Gender"),
        ),
        migrations.AddField(
            model_name="nextofkin",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Age"),
        ),
        migrations.AddField(
            model_name="nextofkin",
            name="gender",
            field=models.CharField(blank=True, max_length=20, verbose_name="Gender"),
        ),
        migrations.AddField(
            model_name="patient",
            name="daycare_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Daycare Number"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="hiv_status",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="HIV / RVD Status"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="ip_op_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hospital Inpatient / Outpatient File Number (e.g. 081/21)",
                max_length=50,
                verbose_name="IP/OP Number",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="referred_by",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Referred By"
            ),
        ),
    ]
