# Generated by Django 5.2.17 on 2026-08-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_caregiver_age_caregiver_caregiver_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="closure_date",
            field=models.DateField(blank=True, null=True, verbose_name="Closure Date"),
        ),
        migrations.AddField(
            model_name="patient",
            name="file_closed",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="File Closed"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="other_medical_notes",
            field=models.TextField(
                blank=True, verbose_name="Other Medical Notes including allergies"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="past_medical_history",
            field=models.TextField(blank=True, verbose_name="Past Medical History"),
        ),
        migrations.AddField(
            model_name="patient",
            name="present_medical_notes",
            field=models.TextField(blank=True, verbose_name="Present Medical Notes"),
        ),
        migrations.AddField(
            model_name="patient",
            name="special_remarks",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Alive", "Alive"),
                    ("Deceased", "Deceased"),
                    ("Unknown", "Unknown"),
                ],
                help_text="Alive, Deceased, Unknown",
                max_length=50,
                verbose_name="Special Remarks",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="cause_of_death",
            field=models.TextField(blank=True, verbose_name="Cause of Death Notes"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_death",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Death"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("CLOSED", "Closed"),
                    ("DISCHARGED", "Discharged"),
                    ("DECEASED", "Deceased"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
