# Generated by Django 5.2.17 on 2026-08-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_patient_closure_date_patient_file_closed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiver",
            name="county",
            field=models.CharField(
                blank=True, default="Nairobi", max_length=100, verbose_name="County"
            ),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="nearest_stage",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nearest Bus Stop / Stage"
            ),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="sub_county",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Sub-County"
            ),
        ),
        migrations.AddField(
            model_name="caregiver",
            name="ward",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ward"),
        ),
        migrations.AddField(
            model_name="nextofkin",
            name="county",
            field=models.CharField(
                blank=True, default="Nairobi", max_length=100, verbose_name="County"
            ),
        ),
        migrations.AddField(
            model_name="nextofkin",
            name="nearest_stage",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nearest Bus Stop / Stage"
            ),
        ),
        migrations.AddField(
            model_name="nextofkin",
            name="sub_county",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Sub-County"
            ),
        ),
        migrations.AddField(
            model_name="nextofkin",
            name="ward",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ward"),
        ),
        migrations.AlterField(
            model_name="caregiver",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Estate / Residence"
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Estate / Residence"
            ),
        ),
    ]
