# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(
                        help_text="Drug name and formulation, e.g. Oral Morphine Solution 5mg/5ml, Paracetamol, Lactulose",
                        max_length=200,
                    ),
                ),
                (
                    "dosage",
                    models.CharField(help_text="e.g. 10 mg (10 ml)", max_length=100),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("ORAL", "Oral (PO)"),
                            ("SUBLINGUAL", "Sublingual (SL)"),
                            ("SUBCUTANEOUS", "Subcutaneous (SC)"),
                            ("INTRAVENOUS", "Intravenous (IV)"),
                            ("TRANSDERMAL", "Transdermal Patch"),
                            ("RECTAL", "Rectal (PR)"),
                            ("TOPICAL", "Topical"),
                            ("INHALED", "Inhalation / Nebulized"),
                        ],
                        default="ORAL",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g. Every 4 hours (q4h) + Breakthrough dose PRN",
                        max_length=100,
                    ),
                ),
                (
                    "indication",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Severe somatic and visceral cancer pain",
                        max_length=200,
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Medication"),
                            ("HELD", "Temporarily Held / Paused"),
                            ("DISCONTINUED", "Discontinued / Ceased"),
                            ("COMPLETED", "Course Completed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("prescriber_name", models.CharField(blank=True, max_length=150)),
                (
                    "instructions_for_caregiver",
                    models.TextField(
                        blank=True,
                        help_text="Caregiver instructions in English/Swahili",
                    ),
                ),
                ("discontinuation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="patients.patient",
                    ),
                ),
                (
                    "prescriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescribed_medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication Record",
                "verbose_name_plural": "Medication Records",
                "ordering": ["-status", "-start_date"],
            },
        ),
    ]
