# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user_email", models.CharField(blank=True, max_length=255)),
                ("user_role", models.CharField(blank=True, max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Sign In"),
                            ("LOGOUT", "User Sign Out"),
                            ("VIEW", "Record Viewed"),
                            ("CREATE", "Record Created"),
                            ("UPDATE", "Record Updated"),
                            ("AMEND", "Clinical Record Amended"),
                            ("DELETE", "Record Deleted"),
                            ("EXPORT", "Data Exported"),
                            ("PERMISSION_CHANGE", "Permissions Changed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(db_index=True, max_length=100)),
                (
                    "resource_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("summary", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
