# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("CLINIC_VISIT", "Hospice Clinic Consultation"),
                            ("HOME_VISIT", "Home Care Visit"),
                            ("TELEPHONE", "Telephone Review"),
                            ("MDT_MEETING", "Multidisciplinary Team Case Review"),
                            ("COUNSELLING", "Psychosocial / Bereavement Session"),
                            ("DAY_CARE", "Day Care Activity"),
                        ],
                        default="CLINIC_VISIT",
                        max_length=30,
                    ),
                ),
                ("scheduled_date", models.DateField(db_index=True)),
                ("scheduled_time", models.TimeField(default="09:00")),
                ("duration_minutes", models.PositiveIntegerField(default=45)),
                (
                    "location",
                    models.CharField(default="Nairobi Hospice", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("MISSED", "Missed / Did Not Attend (DNA)"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="e.g., Routine monthly review, symptom reassessment, home wound dressing",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("outcome_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["scheduled_date", "scheduled_time"],
            },
        ),
    ]
