# Generated by Django 5.2.17 on 2026-08-22 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_mfa_fields"),
        ("appointments", "0002_alter_appointment_options"),
        ("patients", "0004_alter_patient_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "scheduled_date"], name="appt_patient_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["staff_member", "scheduled_date"], name="appt_staff_date_idx"
            ),
        ),
    ]
