# Generated by Django 5.1.15 on 2026-08-20 06:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("CARE_PLAN_DUE", "Care Plan Review Due"),
                            ("FOLLOWUP_OVERDUE", "Overdue Follow-up Visit"),
                            ("PENDING_REFERRAL", "High Priority Referral Pending"),
                            ("PATIENT_ASSIGNED", "Assigned to Patient Care Team"),
                            ("MISSED_APPOINTMENT", "Missed Clinic/Home Appointment"),
                            (
                                "CLINICAL_ALERT",
                                "High Distress Symptom / Clinical Alert",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link_url", models.CharField(blank=True, max_length=255)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
