# Generated by Django 5.1.15 on 2026-08-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("CARE_PLAN_DUE", "Care Plan Review Due"),
                    ("FOLLOWUP_OVERDUE", "Overdue Follow-up Visit"),
                    ("PENDING_REFERRAL", "High Priority Referral Pending"),
                    ("PATIENT_ASSIGNED", "Assigned to Patient Care Team"),
                    ("MISSED_APPOINTMENT", "Missed Clinic/Home Appointment"),
                    ("CLINICAL_ALERT", "High Distress Symptom / Clinical Alert"),
                    ("NEW_PATIENT_REGISTERED", "New Patient Registered"),
                    ("NEW_APPOINTMENT_SCHEDULED", "New Appointment Scheduled"),
                ],
                max_length=30,
            ),
        ),
    ]
